### ISSUE TITLE
研究用コードのリファクタリング&共有

### ISSUE THREAD

**Issue by rooa** [re-born/tasks#15]
### TODO

まとめる。
### 大枠案
- [ ] Crosslingual Information retrieval @rooa
- [ ] Search Cache Store System @taisho6339 
- [ ] Text Segmentation @kadotami 
- [ ] Collaborative Search @pumpkinheader 
- [ ] Queristory -> #12 
- [ ] BCI @Satomist 
- [ ] Paper-organizing tool @sosuke-k

**Comment by rooa** [comment]
word2vecとかみたいに個別のツールごとでも構わないかも。
個人の研究資産単位で管理するメリットは特に(上に書いてみた割には)感じない。

### 現状で考えつくあン
- 上の物をリポジトリ単位で作る
- 前大地と作ってみたグループにそれらリポをアサインする
- グループ経由でリポを参照するようにする
